### ISSUE TITLE
Add directions for installation of mecab and yomichan-mecab-installer

### ISSUE THREAD

**Issue by oudajosefu** [siikamiika/yomichan#1]
I already have mecab installed and I assume the installation of the yomichan-mecab-installer is done by running the install_mecab_for_yomichan.py script. However, this may not be so obvious for others. Additionally, scanning after checking off mecab instead of the default scanning option in the text parsing options works even without installing the yomichan-mecab-installer, which I assume is not how you intended.

**Comment by siikamiika** [comment]
I'm going to work on usability more in the future, and possibly also make the installer download a platform specific mecab binary somewhere to make Python the only dependency for installation. I could also use something like https://www.pyinstaller.org/ to make it even simpler.

> Additionally, scanning after checking off mecab instead of the default scanning option in the text parsing options works even without installing the yomichan-mecab-installer, which I assume is not how you intended.

You're probably seeing the preview text that has no readings or spaces between words. It's actually a bug because normally the parser element content would be made empty if no parser is available, but now it stops because of an exception because mecab is missing. Thanks for catching.

**Comment by siikamiika** [comment]
The bug with enabling mecab has been fixed in the latest commit, and toggling the checkbox also restarts mecab if you have added or remove dictionaries

**Comment by siikamiika** [comment]
Install instructions have been added to https://github.com/siikamiika/yomichan-mecab-installer/, so this issue is resolved.
